// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/options.proto

package options

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

var E_HttpMode = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50056,
	Name:          "httpMode",
	Tag:           "bytes,50056,opt,name=httpMode",
	Filename:      "proto/options.proto",
}

var E_Agregator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50062,
	Name:          "agregator",
	Tag:           "bytes,50062,opt,name=agregator",
	Filename:      "proto/options.proto",
}

var E_Withelist = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50067,
	Name:          "withelist",
	Tag:           "varint,50067,opt,name=withelist",
	Filename:      "proto/options.proto",
}

var E_Foo = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50001,
	Name:          "foo",
	Tag:           "bytes,50001,opt,name=foo",
	Filename:      "proto/options.proto",
}

var E_IsRepo = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50057,
	Name:          "isRepo",
	Tag:           "varint,50057,opt,name=isRepo",
	Filename:      "proto/options.proto",
}

var E_IsEs = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50064,
	Name:          "isEs",
	Tag:           "varint,50064,opt,name=isEs",
	Filename:      "proto/options.proto",
}

var E_IgnoreFieldDb = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50058,
	Name:          "ignoreFieldDb",
	Tag:           "varint,50058,opt,name=ignoreFieldDb",
	Filename:      "proto/options.proto",
}

var E_IsPrimaryKey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50059,
	Name:          "isPrimaryKey",
	Tag:           "varint,50059,opt,name=isPrimaryKey",
	Filename:      "proto/options.proto",
}

var E_Required = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50060,
	Name:          "required",
	Tag:           "varint,50060,opt,name=required",
	Filename:      "proto/options.proto",
}

var E_RequiredType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50061,
	Name:          "required_type",
	Tag:           "bytes,50061,opt,name=required_type,json=requiredType",
	Filename:      "proto/options.proto",
}

var E_Fulltext = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50063,
	Name:          "fulltext",
	Tag:           "varint,50063,opt,name=fulltext",
	Filename:      "proto/options.proto",
}

var E_ErrDesc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50065,
	Name:          "errDesc",
	Tag:           "bytes,50065,opt,name=errDesc",
	Filename:      "proto/options.proto",
}

var E_ForeignKey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50066,
	Name:          "foreignKey",
	Tag:           "bytes,50066,opt,name=foreignKey",
	Filename:      "proto/options.proto",
}

var E_GrpcMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50068,
	Name:          "grpcMethod",
	Tag:           "varint,50068,opt,name=grpcMethod",
	Filename:      "proto/options.proto",
}

var E_ProtoFileLoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50069,
	Name:          "protoFileLoc",
	Tag:           "bytes,50069,opt,name=protoFileLoc",
	Filename:      "proto/options.proto",
}

var E_GrpcAddress = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50070,
	Name:          "grpcAddress",
	Tag:           "bytes,50070,opt,name=grpcAddress",
	Filename:      "proto/options.proto",
}

func init() {
	proto.RegisterExtension(E_HttpMode)
	proto.RegisterExtension(E_Agregator)
	proto.RegisterExtension(E_Withelist)
	proto.RegisterExtension(E_Foo)
	proto.RegisterExtension(E_IsRepo)
	proto.RegisterExtension(E_IsEs)
	proto.RegisterExtension(E_IgnoreFieldDb)
	proto.RegisterExtension(E_IsPrimaryKey)
	proto.RegisterExtension(E_Required)
	proto.RegisterExtension(E_RequiredType)
	proto.RegisterExtension(E_Fulltext)
	proto.RegisterExtension(E_ErrDesc)
	proto.RegisterExtension(E_ForeignKey)
	proto.RegisterExtension(E_GrpcMethod)
	proto.RegisterExtension(E_ProtoFileLoc)
	proto.RegisterExtension(E_GrpcAddress)
}

func init() { proto.RegisterFile("proto/options.proto", fileDescriptor_options_c23a0aa38efb3983) }

var fileDescriptor_options_c23a0aa38efb3983 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0xcb, 0x6e, 0xe2, 0x30,
	0x14, 0x06, 0x60, 0x8d, 0x18, 0x31, 0xe0, 0x81, 0x0d, 0xb3, 0x19, 0x8d, 0x34, 0x2d, 0xcb, 0xae,
	0xc2, 0x02, 0x75, 0x81, 0x5b, 0xb5, 0x42, 0x05, 0x36, 0x2d, 0x6a, 0x85, 0xba, 0xaf, 0x02, 0x39,
	0x31, 0x96, 0x52, 0xec, 0x1e, 0x1b, 0xb5, 0x79, 0x81, 0xde, 0xef, 0xb7, 0xf7, 0xea, 0x1b, 0x55,
	0x49, 0x6c, 0x08, 0x6a, 0x25, 0xb3, 0x8b, 0x95, 0xff, 0xfb, 0x7d, 0x62, 0x87, 0xfc, 0x91, 0x28,
	0xb4, 0x68, 0x08, 0xa9, 0xb9, 0x98, 0x28, 0x2f, 0x5d, 0xfd, 0xab, 0x33, 0x21, 0x58, 0x04, 0x8d,
	0x74, 0x35, 0x9c, 0x86, 0x8d, 0x00, 0xd4, 0x08, 0xb9, 0xd4, 0x02, 0xb3, 0x04, 0xdd, 0x24, 0xa5,
	0xb1, 0xd6, 0xb2, 0x2f, 0x02, 0xa8, 0xad, 0x78, 0x59, 0xdc, 0xb3, 0x71, 0xaf, 0x0f, 0x7a, 0x2c,
	0x82, 0xfd, 0xac, 0xf3, 0xef, 0xe5, 0x45, 0xa1, 0xfe, 0x63, 0xad, 0x3c, 0x98, 0x09, 0xba, 0x45,
	0xca, 0x3e, 0x43, 0x60, 0xbe, 0x16, 0xe8, 0xe4, 0xf7, 0x86, 0xcf, 0x49, 0xe2, 0x4f, 0xb9, 0x1e,
	0x43, 0xc4, 0x95, 0x76, 0xfa, 0x97, 0xd4, 0x97, 0x06, 0x73, 0x42, 0x9b, 0xa4, 0x10, 0x0a, 0x51,
	0x5b, 0xfd, 0x46, 0x2a, 0xe5, 0x33, 0xb0, 0xf4, 0xe3, 0x3c, 0xdb, 0x3a, 0x49, 0xd3, 0x16, 0x29,
	0x72, 0x35, 0x00, 0xb9, 0x84, 0xbb, 0x32, 0x5b, 0x1a, 0x40, 0xd7, 0xc9, 0x4f, 0xae, 0xba, 0xca,
	0x0d, 0x1f, 0x0d, 0x4c, 0xe3, 0xb4, 0x4b, 0xaa, 0x9c, 0x4d, 0x04, 0x42, 0x8f, 0x43, 0x14, 0x74,
	0x86, 0xb5, 0xff, 0x5f, 0x7c, 0xfa, 0xc6, 0xea, 0x6b, 0xa3, 0x17, 0x15, 0xdd, 0x21, 0x15, 0xae,
	0x0e, 0x90, 0x1f, 0xfb, 0x18, 0xef, 0x42, 0xec, 0x6a, 0xb9, 0x31, 0x2d, 0x0b, 0x88, 0x6e, 0x90,
	0x12, 0xc2, 0xc9, 0x94, 0x23, 0x04, 0xae, 0x82, 0x5b, 0x53, 0x30, 0x03, 0xb4, 0x43, 0xaa, 0xf6,
	0xf9, 0x48, 0xc7, 0x12, 0x5c, 0x0d, 0x77, 0xe6, 0xca, 0x2b, 0x56, 0x1d, 0xc6, 0x12, 0x92, 0x11,
	0xc2, 0x69, 0x14, 0x69, 0x38, 0xd3, 0xae, 0x82, 0x07, 0x3b, 0x82, 0x05, 0xb4, 0x45, 0x7e, 0x01,
	0x62, 0x07, 0xd4, 0xc8, 0x65, 0x9f, 0xcc, 0xe6, 0x36, 0x4f, 0xb7, 0x09, 0x09, 0x05, 0x02, 0x67,
	0x93, 0x25, 0x4e, 0xef, 0xd9, 0xe8, 0x1c, 0x49, 0x0a, 0x18, 0xca, 0x51, 0xf6, 0x5b, 0xba, 0x0a,
	0x5e, 0xcd, 0xe8, 0x39, 0x92, 0xdc, 0x60, 0x1a, 0xee, 0xf1, 0x08, 0xf6, 0x84, 0xf3, 0x0b, 0xde,
	0xec, 0xf1, 0xe5, 0x11, 0x6d, 0x93, 0xdf, 0x49, 0x65, 0x3b, 0x08, 0x10, 0x94, 0x72, 0x75, 0xbc,
	0x9b, 0x8e, 0xbc, 0x19, 0x16, 0xd3, 0x6c, 0xf3, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x2f, 0xf5,
	0x9d, 0x35, 0x04, 0x00, 0x00,
}
